/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AddressRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7668172942191631727L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AddressRecord\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"fields\":[{\"name\":\"street_number\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AddressRecord> ENCODER =
      new BinaryMessageEncoder<AddressRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AddressRecord> DECODER =
      new BinaryMessageDecoder<AddressRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AddressRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AddressRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AddressRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AddressRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AddressRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AddressRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AddressRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AddressRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int street_number;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AddressRecord() {}

  /**
   * All-args constructor.
   * @param street_number The new value for street_number
   */
  public AddressRecord(java.lang.Integer street_number) {
    this.street_number = street_number;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return street_number;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: street_number = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'street_number' field.
   * @return The value of the 'street_number' field.
   */
  public int getStreetNumber() {
    return street_number;
  }


  /**
   * Sets the value of the 'street_number' field.
   * @param value the value to set.
   */
  public void setStreetNumber(int value) {
    this.street_number = value;
  }

  /**
   * Creates a new AddressRecord RecordBuilder.
   * @return A new AddressRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.AddressRecord.Builder newBuilder() {
    return new com.google.cloud.pubsub.prober.AddressRecord.Builder();
  }

  /**
   * Creates a new AddressRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AddressRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.AddressRecord.Builder newBuilder(com.google.cloud.pubsub.prober.AddressRecord.Builder other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.AddressRecord.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.AddressRecord.Builder(other);
    }
  }

  /**
   * Creates a new AddressRecord RecordBuilder by copying an existing AddressRecord instance.
   * @param other The existing instance to copy.
   * @return A new AddressRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.AddressRecord.Builder newBuilder(com.google.cloud.pubsub.prober.AddressRecord other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.AddressRecord.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.AddressRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for AddressRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AddressRecord>
    implements org.apache.avro.data.RecordBuilder<AddressRecord> {

    private int street_number;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.AddressRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.street_number)) {
        this.street_number = data().deepCopy(fields()[0].schema(), other.street_number);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AddressRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.AddressRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.street_number)) {
        this.street_number = data().deepCopy(fields()[0].schema(), other.street_number);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'street_number' field.
      * @return The value.
      */
    public int getStreetNumber() {
      return street_number;
    }


    /**
      * Sets the value of the 'street_number' field.
      * @param value The value of 'street_number'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.AddressRecord.Builder setStreetNumber(int value) {
      validate(fields()[0], value);
      this.street_number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'street_number' field has been set.
      * @return True if the 'street_number' field has been set, false otherwise.
      */
    public boolean hasStreetNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'street_number' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.AddressRecord.Builder clearStreetNumber() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AddressRecord build() {
      try {
        AddressRecord record = new AddressRecord();
        record.street_number = fieldSetFlags()[0] ? this.street_number : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AddressRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<AddressRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AddressRecord>
    READER$ = (org.apache.avro.io.DatumReader<AddressRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.street_number);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.street_number = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.street_number = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










