/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Avro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -727814076044055653L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Avro\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"fields\":[{\"name\":\"TestStringField\",\"type\":\"string\"},{\"name\":\"TestIntField\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Avro> ENCODER =
      new BinaryMessageEncoder<Avro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Avro> DECODER =
      new BinaryMessageDecoder<Avro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Avro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Avro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Avro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Avro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Avro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Avro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Avro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Avro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence TestStringField;
   private int TestIntField;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Avro() {}

  /**
   * All-args constructor.
   * @param TestStringField The new value for TestStringField
   * @param TestIntField The new value for TestIntField
   */
  public Avro(java.lang.CharSequence TestStringField, java.lang.Integer TestIntField) {
    this.TestStringField = TestStringField;
    this.TestIntField = TestIntField;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return TestStringField;
    case 1: return TestIntField;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: TestStringField = (java.lang.CharSequence)value$; break;
    case 1: TestIntField = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'TestStringField' field.
   * @return The value of the 'TestStringField' field.
   */
  public java.lang.CharSequence getTestStringField() {
    return TestStringField;
  }


  /**
   * Sets the value of the 'TestStringField' field.
   * @param value the value to set.
   */
  public void setTestStringField(java.lang.CharSequence value) {
    this.TestStringField = value;
  }

  /**
   * Gets the value of the 'TestIntField' field.
   * @return The value of the 'TestIntField' field.
   */
  public int getTestIntField() {
    return TestIntField;
  }


  /**
   * Sets the value of the 'TestIntField' field.
   * @param value the value to set.
   */
  public void setTestIntField(int value) {
    this.TestIntField = value;
  }

  /**
   * Creates a new Avro RecordBuilder.
   * @return A new Avro RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.Avro.Builder newBuilder() {
    return new com.google.cloud.pubsub.prober.Avro.Builder();
  }

  /**
   * Creates a new Avro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Avro RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.Avro.Builder newBuilder(com.google.cloud.pubsub.prober.Avro.Builder other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.Avro.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.Avro.Builder(other);
    }
  }

  /**
   * Creates a new Avro RecordBuilder by copying an existing Avro instance.
   * @param other The existing instance to copy.
   * @return A new Avro RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.Avro.Builder newBuilder(com.google.cloud.pubsub.prober.Avro other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.Avro.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.Avro.Builder(other);
    }
  }

  /**
   * RecordBuilder for Avro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Avro>
    implements org.apache.avro.data.RecordBuilder<Avro> {

    private java.lang.CharSequence TestStringField;
    private int TestIntField;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.Avro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.TestStringField)) {
        this.TestStringField = data().deepCopy(fields()[0].schema(), other.TestStringField);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.TestIntField)) {
        this.TestIntField = data().deepCopy(fields()[1].schema(), other.TestIntField);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Avro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.Avro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.TestStringField)) {
        this.TestStringField = data().deepCopy(fields()[0].schema(), other.TestStringField);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.TestIntField)) {
        this.TestIntField = data().deepCopy(fields()[1].schema(), other.TestIntField);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'TestStringField' field.
      * @return The value.
      */
    public java.lang.CharSequence getTestStringField() {
      return TestStringField;
    }


    /**
      * Sets the value of the 'TestStringField' field.
      * @param value The value of 'TestStringField'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.Avro.Builder setTestStringField(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.TestStringField = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'TestStringField' field has been set.
      * @return True if the 'TestStringField' field has been set, false otherwise.
      */
    public boolean hasTestStringField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'TestStringField' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.Avro.Builder clearTestStringField() {
      TestStringField = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'TestIntField' field.
      * @return The value.
      */
    public int getTestIntField() {
      return TestIntField;
    }


    /**
      * Sets the value of the 'TestIntField' field.
      * @param value The value of 'TestIntField'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.Avro.Builder setTestIntField(int value) {
      validate(fields()[1], value);
      this.TestIntField = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'TestIntField' field has been set.
      * @return True if the 'TestIntField' field has been set, false otherwise.
      */
    public boolean hasTestIntField() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'TestIntField' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.Avro.Builder clearTestIntField() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Avro build() {
      try {
        Avro record = new Avro();
        record.TestStringField = fieldSetFlags()[0] ? this.TestStringField : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.TestIntField = fieldSetFlags()[1] ? this.TestIntField : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Avro>
    WRITER$ = (org.apache.avro.io.DatumWriter<Avro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Avro>
    READER$ = (org.apache.avro.io.DatumReader<Avro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.TestStringField);

    out.writeInt(this.TestIntField);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.TestStringField = in.readString(this.TestStringField instanceof Utf8 ? (Utf8)this.TestStringField : null);

      this.TestIntField = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.TestStringField = in.readString(this.TestStringField instanceof Utf8 ? (Utf8)this.TestStringField : null);
          break;

        case 1:
          this.TestIntField = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










