// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto
package com.google.cloud.pubsub.prober;

public final class Defaults {
  private Defaults() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExampleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ExampleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string defaultstr = 1;</code>
     * @return The defaultstr.
     */
    java.lang.String getDefaultstr();
    /**
     * <code>string defaultstr = 1;</code>
     * @return The bytes for defaultstr.
     */
    com.google.protobuf.ByteString
        getDefaultstrBytes();

    /**
     * <code>bool defaultbool = 2;</code>
     * @return The defaultbool.
     */
    boolean getDefaultbool();
  }
  /**
   * Protobuf type {@code ExampleMessage}
   */
  public static final class ExampleMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ExampleMessage)
      ExampleMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExampleMessage.newBuilder() to construct.
    private ExampleMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExampleMessage() {
      defaultstr_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ExampleMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExampleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              defaultstr_ = s;
              break;
            }
            case 16: {

              defaultbool_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Defaults.internal_static_ExampleMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Defaults.internal_static_ExampleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Defaults.ExampleMessage.class, Defaults.ExampleMessage.Builder.class);
    }

    public static final int DEFAULTSTR_FIELD_NUMBER = 1;
    private volatile java.lang.Object defaultstr_;
    /**
     * <code>string defaultstr = 1;</code>
     * @return The defaultstr.
     */
    @java.lang.Override
    public java.lang.String getDefaultstr() {
      java.lang.Object ref = defaultstr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultstr_ = s;
        return s;
      }
    }
    /**
     * <code>string defaultstr = 1;</code>
     * @return The bytes for defaultstr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDefaultstrBytes() {
      java.lang.Object ref = defaultstr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultstr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULTBOOL_FIELD_NUMBER = 2;
    private boolean defaultbool_;
    /**
     * <code>bool defaultbool = 2;</code>
     * @return The defaultbool.
     */
    @java.lang.Override
    public boolean getDefaultbool() {
      return defaultbool_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDefaultstrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, defaultstr_);
      }
      if (defaultbool_ != false) {
        output.writeBool(2, defaultbool_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDefaultstrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, defaultstr_);
      }
      if (defaultbool_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, defaultbool_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Defaults.ExampleMessage)) {
        return super.equals(obj);
      }
      Defaults.ExampleMessage other = (Defaults.ExampleMessage) obj;

      if (!getDefaultstr()
          .equals(other.getDefaultstr())) return false;
      if (getDefaultbool()
          != other.getDefaultbool()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEFAULTSTR_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultstr().hashCode();
      hash = (37 * hash) + DEFAULTBOOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDefaultbool());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Defaults.ExampleMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Defaults.ExampleMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Defaults.ExampleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Defaults.ExampleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Defaults.ExampleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Defaults.ExampleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Defaults.ExampleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Defaults.ExampleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Defaults.ExampleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Defaults.ExampleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Defaults.ExampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Defaults.ExampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Defaults.ExampleMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExampleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ExampleMessage)
        Defaults.ExampleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Defaults.internal_static_ExampleMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Defaults.internal_static_ExampleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Defaults.ExampleMessage.class, Defaults.ExampleMessage.Builder.class);
      }

      // Construct using Defaults.ExampleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        defaultstr_ = "";

        defaultbool_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Defaults.internal_static_ExampleMessage_descriptor;
      }

      @java.lang.Override
      public Defaults.ExampleMessage getDefaultInstanceForType() {
        return Defaults.ExampleMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Defaults.ExampleMessage build() {
        Defaults.ExampleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Defaults.ExampleMessage buildPartial() {
        Defaults.ExampleMessage result = new Defaults.ExampleMessage(this);
        result.defaultstr_ = defaultstr_;
        result.defaultbool_ = defaultbool_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Defaults.ExampleMessage) {
          return mergeFrom((Defaults.ExampleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Defaults.ExampleMessage other) {
        if (other == Defaults.ExampleMessage.getDefaultInstance()) return this;
        if (!other.getDefaultstr().isEmpty()) {
          defaultstr_ = other.defaultstr_;
          onChanged();
        }
        if (other.getDefaultbool() != false) {
          setDefaultbool(other.getDefaultbool());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Defaults.ExampleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Defaults.ExampleMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object defaultstr_ = "";
      /**
       * <code>string defaultstr = 1;</code>
       * @return The defaultstr.
       */
      public java.lang.String getDefaultstr() {
        java.lang.Object ref = defaultstr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          defaultstr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string defaultstr = 1;</code>
       * @return The bytes for defaultstr.
       */
      public com.google.protobuf.ByteString
          getDefaultstrBytes() {
        java.lang.Object ref = defaultstr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          defaultstr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string defaultstr = 1;</code>
       * @param value The defaultstr to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultstr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        defaultstr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string defaultstr = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultstr() {

        defaultstr_ = getDefaultInstance().getDefaultstr();
        onChanged();
        return this;
      }
      /**
       * <code>string defaultstr = 1;</code>
       * @param value The bytes for defaultstr to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultstrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        defaultstr_ = value;
        onChanged();
        return this;
      }

      private boolean defaultbool_ ;
      /**
       * <code>bool defaultbool = 2;</code>
       * @return The defaultbool.
       */
      @java.lang.Override
      public boolean getDefaultbool() {
        return defaultbool_;
      }
      /**
       * <code>bool defaultbool = 2;</code>
       * @param value The defaultbool to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultbool(boolean value) {

        defaultbool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool defaultbool = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultbool() {

        defaultbool_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ExampleMessage)
    }

    // @@protoc_insertion_point(class_scope:ExampleMessage)
    private static final Defaults.ExampleMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Defaults.ExampleMessage();
    }

    public static Defaults.ExampleMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleMessage>
        PARSER = new com.google.protobuf.AbstractParser<ExampleMessage>() {
      @java.lang.Override
      public ExampleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExampleMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExampleMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Defaults.ExampleMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExampleMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExampleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016defaults.proto\"9\n\016ExampleMessage\022\022\n\nde" +
      "faultstr\030\001 \001(\t\022\023\n\013defaultbool\030\002 \001(\010b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ExampleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExampleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExampleMessage_descriptor,
        new java.lang.String[] { "Defaultstr", "Defaultbool", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
