/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EnumRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3278200841456387676L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnumRecord\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"fields\":[{\"name\":\"string_field\",\"type\":\"string\"},{\"name\":\"enum_field\",\"type\":{\"type\":\"enum\",\"name\":\"Suit\",\"symbols\":[\"SPADES\",\"HEARTS\",\"DIAMONDS\",\"CLUBS\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EnumRecord> ENCODER =
      new BinaryMessageEncoder<EnumRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EnumRecord> DECODER =
      new BinaryMessageDecoder<EnumRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EnumRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EnumRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EnumRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EnumRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EnumRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EnumRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EnumRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EnumRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence string_field;
   private com.google.cloud.pubsub.prober.Suit enum_field;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EnumRecord() {}

  /**
   * All-args constructor.
   * @param string_field The new value for string_field
   * @param enum_field The new value for enum_field
   */
  public EnumRecord(java.lang.CharSequence string_field, com.google.cloud.pubsub.prober.Suit enum_field) {
    this.string_field = string_field;
    this.enum_field = enum_field;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return string_field;
    case 1: return enum_field;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: string_field = (java.lang.CharSequence)value$; break;
    case 1: enum_field = (com.google.cloud.pubsub.prober.Suit)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'string_field' field.
   * @return The value of the 'string_field' field.
   */
  public java.lang.CharSequence getStringField() {
    return string_field;
  }


  /**
   * Sets the value of the 'string_field' field.
   * @param value the value to set.
   */
  public void setStringField(java.lang.CharSequence value) {
    this.string_field = value;
  }

  /**
   * Gets the value of the 'enum_field' field.
   * @return The value of the 'enum_field' field.
   */
  public com.google.cloud.pubsub.prober.Suit getEnumField() {
    return enum_field;
  }


  /**
   * Sets the value of the 'enum_field' field.
   * @param value the value to set.
   */
  public void setEnumField(com.google.cloud.pubsub.prober.Suit value) {
    this.enum_field = value;
  }

  /**
   * Creates a new EnumRecord RecordBuilder.
   * @return A new EnumRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.EnumRecord.Builder newBuilder() {
    return new com.google.cloud.pubsub.prober.EnumRecord.Builder();
  }

  /**
   * Creates a new EnumRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EnumRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.EnumRecord.Builder newBuilder(com.google.cloud.pubsub.prober.EnumRecord.Builder other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.EnumRecord.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.EnumRecord.Builder(other);
    }
  }

  /**
   * Creates a new EnumRecord RecordBuilder by copying an existing EnumRecord instance.
   * @param other The existing instance to copy.
   * @return A new EnumRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.EnumRecord.Builder newBuilder(com.google.cloud.pubsub.prober.EnumRecord other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.EnumRecord.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.EnumRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for EnumRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnumRecord>
    implements org.apache.avro.data.RecordBuilder<EnumRecord> {

    private java.lang.CharSequence string_field;
    private com.google.cloud.pubsub.prober.Suit enum_field;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.EnumRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.string_field)) {
        this.string_field = data().deepCopy(fields()[0].schema(), other.string_field);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.enum_field)) {
        this.enum_field = data().deepCopy(fields()[1].schema(), other.enum_field);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing EnumRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.EnumRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.string_field)) {
        this.string_field = data().deepCopy(fields()[0].schema(), other.string_field);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.enum_field)) {
        this.enum_field = data().deepCopy(fields()[1].schema(), other.enum_field);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'string_field' field.
      * @return The value.
      */
    public java.lang.CharSequence getStringField() {
      return string_field;
    }


    /**
      * Sets the value of the 'string_field' field.
      * @param value The value of 'string_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.EnumRecord.Builder setStringField(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.string_field = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'string_field' field has been set.
      * @return True if the 'string_field' field has been set, false otherwise.
      */
    public boolean hasStringField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'string_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.EnumRecord.Builder clearStringField() {
      string_field = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'enum_field' field.
      * @return The value.
      */
    public com.google.cloud.pubsub.prober.Suit getEnumField() {
      return enum_field;
    }


    /**
      * Sets the value of the 'enum_field' field.
      * @param value The value of 'enum_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.EnumRecord.Builder setEnumField(com.google.cloud.pubsub.prober.Suit value) {
      validate(fields()[1], value);
      this.enum_field = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'enum_field' field has been set.
      * @return True if the 'enum_field' field has been set, false otherwise.
      */
    public boolean hasEnumField() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'enum_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.EnumRecord.Builder clearEnumField() {
      enum_field = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EnumRecord build() {
      try {
        EnumRecord record = new EnumRecord();
        record.string_field = fieldSetFlags()[0] ? this.string_field : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.enum_field = fieldSetFlags()[1] ? this.enum_field : (com.google.cloud.pubsub.prober.Suit) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EnumRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<EnumRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EnumRecord>
    READER$ = (org.apache.avro.io.DatumReader<EnumRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.string_field);

    out.writeEnum(this.enum_field.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.string_field = in.readString(this.string_field instanceof Utf8 ? (Utf8)this.string_field : null);

      this.enum_field = com.google.cloud.pubsub.prober.Suit.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.string_field = in.readString(this.string_field instanceof Utf8 ? (Utf8)this.string_field : null);
          break;

        case 1:
          this.enum_field = com.google.cloud.pubsub.prober.Suit.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










