/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LongRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8267241968982148338L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LongRecord\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"fields\":[{\"name\":\"longvalue\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LongRecord> ENCODER =
      new BinaryMessageEncoder<LongRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LongRecord> DECODER =
      new BinaryMessageDecoder<LongRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LongRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LongRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LongRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LongRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LongRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LongRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LongRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LongRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long longvalue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LongRecord() {}

  /**
   * All-args constructor.
   * @param longvalue The new value for longvalue
   */
  public LongRecord(java.lang.Long longvalue) {
    this.longvalue = longvalue;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return longvalue;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: longvalue = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'longvalue' field.
   * @return The value of the 'longvalue' field.
   */
  public long getLongvalue() {
    return longvalue;
  }


  /**
   * Sets the value of the 'longvalue' field.
   * @param value the value to set.
   */
  public void setLongvalue(long value) {
    this.longvalue = value;
  }

  /**
   * Creates a new LongRecord RecordBuilder.
   * @return A new LongRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.LongRecord.Builder newBuilder() {
    return new com.google.cloud.pubsub.prober.LongRecord.Builder();
  }

  /**
   * Creates a new LongRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LongRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.LongRecord.Builder newBuilder(com.google.cloud.pubsub.prober.LongRecord.Builder other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.LongRecord.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.LongRecord.Builder(other);
    }
  }

  /**
   * Creates a new LongRecord RecordBuilder by copying an existing LongRecord instance.
   * @param other The existing instance to copy.
   * @return A new LongRecord RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.LongRecord.Builder newBuilder(com.google.cloud.pubsub.prober.LongRecord other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.LongRecord.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.LongRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for LongRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LongRecord>
    implements org.apache.avro.data.RecordBuilder<LongRecord> {

    private long longvalue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.LongRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.longvalue)) {
        this.longvalue = data().deepCopy(fields()[0].schema(), other.longvalue);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing LongRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.LongRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.longvalue)) {
        this.longvalue = data().deepCopy(fields()[0].schema(), other.longvalue);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'longvalue' field.
      * @return The value.
      */
    public long getLongvalue() {
      return longvalue;
    }


    /**
      * Sets the value of the 'longvalue' field.
      * @param value The value of 'longvalue'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.LongRecord.Builder setLongvalue(long value) {
      validate(fields()[0], value);
      this.longvalue = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'longvalue' field has been set.
      * @return True if the 'longvalue' field has been set, false otherwise.
      */
    public boolean hasLongvalue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'longvalue' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.LongRecord.Builder clearLongvalue() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LongRecord build() {
      try {
        LongRecord record = new LongRecord();
        record.longvalue = fieldSetFlags()[0] ? this.longvalue : (java.lang.Long) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LongRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<LongRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LongRecord>
    READER$ = (org.apache.avro.io.DatumReader<LongRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.longvalue);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.longvalue = in.readLong();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.longvalue = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










