/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 163982016061859201L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"fields\":[{\"name\":\"time_micros_field\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-micros\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMicrosConversion());
  }

  private static final BinaryMessageEncoder<Message> ENCODER =
      new BinaryMessageEncoder<Message>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Message> DECODER =
      new BinaryMessageDecoder<Message>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Message> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Message> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Message> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Message>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Message to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Message from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Message instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Message fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.time.Instant time_micros_field;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Message() {}

  /**
   * All-args constructor.
   * @param time_micros_field The new value for time_micros_field
   */
  public Message(java.time.Instant time_micros_field) {
    this.time_micros_field = time_micros_field.truncatedTo(java.time.temporal.ChronoUnit.MICROS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time_micros_field;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.data.TimeConversions.TimestampMicrosConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time_micros_field = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'time_micros_field' field.
   * @return The value of the 'time_micros_field' field.
   */
  public java.time.Instant getTimeMicrosField() {
    return time_micros_field;
  }


  /**
   * Sets the value of the 'time_micros_field' field.
   * @param value the value to set.
   */
  public void setTimeMicrosField(java.time.Instant value) {
    this.time_micros_field = value.truncatedTo(java.time.temporal.ChronoUnit.MICROS);
  }

  /**
   * Creates a new Message RecordBuilder.
   * @return A new Message RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.Message.Builder newBuilder() {
    return new com.google.cloud.pubsub.prober.Message.Builder();
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Message RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.Message.Builder newBuilder(com.google.cloud.pubsub.prober.Message.Builder other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.Message.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.Message.Builder(other);
    }
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Message instance.
   * @param other The existing instance to copy.
   * @return A new Message RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.Message.Builder newBuilder(com.google.cloud.pubsub.prober.Message other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.Message.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.Message.Builder(other);
    }
  }

  /**
   * RecordBuilder for Message instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.time.Instant time_micros_field;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time_micros_field)) {
        this.time_micros_field = data().deepCopy(fields()[0].schema(), other.time_micros_field);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Message instance
     * @param other The existing instance to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.Message other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.time_micros_field)) {
        this.time_micros_field = data().deepCopy(fields()[0].schema(), other.time_micros_field);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'time_micros_field' field.
      * @return The value.
      */
    public java.time.Instant getTimeMicrosField() {
      return time_micros_field;
    }


    /**
      * Sets the value of the 'time_micros_field' field.
      * @param value The value of 'time_micros_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.Message.Builder setTimeMicrosField(java.time.Instant value) {
      validate(fields()[0], value);
      this.time_micros_field = value.truncatedTo(java.time.temporal.ChronoUnit.MICROS);
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time_micros_field' field has been set.
      * @return True if the 'time_micros_field' field has been set, false otherwise.
      */
    public boolean hasTimeMicrosField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time_micros_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.Message.Builder clearTimeMicrosField() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Message build() {
      try {
        Message record = new Message();
        record.time_micros_field = fieldSetFlags()[0] ? this.time_micros_field : (java.time.Instant) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Message>
    WRITER$ = (org.apache.avro.io.DatumWriter<Message>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Message>
    READER$ = (org.apache.avro.io.DatumReader<Message>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










