/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NullTest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5696970414766076000L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NullTest\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"fields\":[{\"name\":\"str_field\",\"type\":[\"null\",\"string\"]},{\"name\":\"int_field\",\"type\":[\"null\",\"int\"]},{\"name\":\"array_field\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\",\"default\":[]}]},{\"name\":\"enum_field\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"Suit\",\"symbols\":[\"SPADES\",\"HEARTS\",\"DIAMONDS\",\"CLUBS\"]}]},{\"name\":\"map_field\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"long\",\"default\":{}}]},{\"name\":\"record_field\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"AddressRecord\",\"fields\":[{\"name\":\"street_number\",\"type\":\"int\"}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NullTest> ENCODER =
      new BinaryMessageEncoder<NullTest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NullTest> DECODER =
      new BinaryMessageDecoder<NullTest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NullTest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NullTest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NullTest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NullTest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NullTest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NullTest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NullTest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NullTest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence str_field;
   private java.lang.Integer int_field;
   private java.util.List<java.lang.CharSequence> array_field;
   private com.google.cloud.pubsub.prober.Suit enum_field;
   private java.util.Map<java.lang.CharSequence,java.lang.Long> map_field;
   private com.google.cloud.pubsub.prober.AddressRecord record_field;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NullTest() {}

  /**
   * All-args constructor.
   * @param str_field The new value for str_field
   * @param int_field The new value for int_field
   * @param array_field The new value for array_field
   * @param enum_field The new value for enum_field
   * @param map_field The new value for map_field
   * @param record_field The new value for record_field
   */
  public NullTest(java.lang.CharSequence str_field, java.lang.Integer int_field, java.util.List<java.lang.CharSequence> array_field, com.google.cloud.pubsub.prober.Suit enum_field, java.util.Map<java.lang.CharSequence,java.lang.Long> map_field, com.google.cloud.pubsub.prober.AddressRecord record_field) {
    this.str_field = str_field;
    this.int_field = int_field;
    this.array_field = array_field;
    this.enum_field = enum_field;
    this.map_field = map_field;
    this.record_field = record_field;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return str_field;
    case 1: return int_field;
    case 2: return array_field;
    case 3: return enum_field;
    case 4: return map_field;
    case 5: return record_field;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: str_field = (java.lang.CharSequence)value$; break;
    case 1: int_field = (java.lang.Integer)value$; break;
    case 2: array_field = (java.util.List<java.lang.CharSequence>)value$; break;
    case 3: enum_field = (com.google.cloud.pubsub.prober.Suit)value$; break;
    case 4: map_field = (java.util.Map<java.lang.CharSequence,java.lang.Long>)value$; break;
    case 5: record_field = (com.google.cloud.pubsub.prober.AddressRecord)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'str_field' field.
   * @return The value of the 'str_field' field.
   */
  public java.lang.CharSequence getStrField() {
    return str_field;
  }


  /**
   * Sets the value of the 'str_field' field.
   * @param value the value to set.
   */
  public void setStrField(java.lang.CharSequence value) {
    this.str_field = value;
  }

  /**
   * Gets the value of the 'int_field' field.
   * @return The value of the 'int_field' field.
   */
  public java.lang.Integer getIntField() {
    return int_field;
  }


  /**
   * Sets the value of the 'int_field' field.
   * @param value the value to set.
   */
  public void setIntField(java.lang.Integer value) {
    this.int_field = value;
  }

  /**
   * Gets the value of the 'array_field' field.
   * @return The value of the 'array_field' field.
   */
  public java.util.List<java.lang.CharSequence> getArrayField() {
    return array_field;
  }


  /**
   * Sets the value of the 'array_field' field.
   * @param value the value to set.
   */
  public void setArrayField(java.util.List<java.lang.CharSequence> value) {
    this.array_field = value;
  }

  /**
   * Gets the value of the 'enum_field' field.
   * @return The value of the 'enum_field' field.
   */
  public com.google.cloud.pubsub.prober.Suit getEnumField() {
    return enum_field;
  }


  /**
   * Sets the value of the 'enum_field' field.
   * @param value the value to set.
   */
  public void setEnumField(com.google.cloud.pubsub.prober.Suit value) {
    this.enum_field = value;
  }

  /**
   * Gets the value of the 'map_field' field.
   * @return The value of the 'map_field' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Long> getMapField() {
    return map_field;
  }


  /**
   * Sets the value of the 'map_field' field.
   * @param value the value to set.
   */
  public void setMapField(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
    this.map_field = value;
  }

  /**
   * Gets the value of the 'record_field' field.
   * @return The value of the 'record_field' field.
   */
  public com.google.cloud.pubsub.prober.AddressRecord getRecordField() {
    return record_field;
  }


  /**
   * Sets the value of the 'record_field' field.
   * @param value the value to set.
   */
  public void setRecordField(com.google.cloud.pubsub.prober.AddressRecord value) {
    this.record_field = value;
  }

  /**
   * Creates a new NullTest RecordBuilder.
   * @return A new NullTest RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.NullTest.Builder newBuilder() {
    return new com.google.cloud.pubsub.prober.NullTest.Builder();
  }

  /**
   * Creates a new NullTest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NullTest RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.NullTest.Builder newBuilder(com.google.cloud.pubsub.prober.NullTest.Builder other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.NullTest.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.NullTest.Builder(other);
    }
  }

  /**
   * Creates a new NullTest RecordBuilder by copying an existing NullTest instance.
   * @param other The existing instance to copy.
   * @return A new NullTest RecordBuilder
   */
  public static com.google.cloud.pubsub.prober.NullTest.Builder newBuilder(com.google.cloud.pubsub.prober.NullTest other) {
    if (other == null) {
      return new com.google.cloud.pubsub.prober.NullTest.Builder();
    } else {
      return new com.google.cloud.pubsub.prober.NullTest.Builder(other);
    }
  }

  /**
   * RecordBuilder for NullTest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NullTest>
    implements org.apache.avro.data.RecordBuilder<NullTest> {

    private java.lang.CharSequence str_field;
    private java.lang.Integer int_field;
    private java.util.List<java.lang.CharSequence> array_field;
    private com.google.cloud.pubsub.prober.Suit enum_field;
    private java.util.Map<java.lang.CharSequence,java.lang.Long> map_field;
    private com.google.cloud.pubsub.prober.AddressRecord record_field;
    private com.google.cloud.pubsub.prober.AddressRecord.Builder record_fieldBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.NullTest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.str_field)) {
        this.str_field = data().deepCopy(fields()[0].schema(), other.str_field);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.int_field)) {
        this.int_field = data().deepCopy(fields()[1].schema(), other.int_field);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.array_field)) {
        this.array_field = data().deepCopy(fields()[2].schema(), other.array_field);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.enum_field)) {
        this.enum_field = data().deepCopy(fields()[3].schema(), other.enum_field);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.map_field)) {
        this.map_field = data().deepCopy(fields()[4].schema(), other.map_field);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.record_field)) {
        this.record_field = data().deepCopy(fields()[5].schema(), other.record_field);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasRecordFieldBuilder()) {
        this.record_fieldBuilder = com.google.cloud.pubsub.prober.AddressRecord.newBuilder(other.getRecordFieldBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing NullTest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.google.cloud.pubsub.prober.NullTest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.str_field)) {
        this.str_field = data().deepCopy(fields()[0].schema(), other.str_field);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.int_field)) {
        this.int_field = data().deepCopy(fields()[1].schema(), other.int_field);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.array_field)) {
        this.array_field = data().deepCopy(fields()[2].schema(), other.array_field);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.enum_field)) {
        this.enum_field = data().deepCopy(fields()[3].schema(), other.enum_field);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.map_field)) {
        this.map_field = data().deepCopy(fields()[4].schema(), other.map_field);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.record_field)) {
        this.record_field = data().deepCopy(fields()[5].schema(), other.record_field);
        fieldSetFlags()[5] = true;
      }
      this.record_fieldBuilder = null;
    }

    /**
      * Gets the value of the 'str_field' field.
      * @return The value.
      */
    public java.lang.CharSequence getStrField() {
      return str_field;
    }


    /**
      * Sets the value of the 'str_field' field.
      * @param value The value of 'str_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder setStrField(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.str_field = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'str_field' field has been set.
      * @return True if the 'str_field' field has been set, false otherwise.
      */
    public boolean hasStrField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'str_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder clearStrField() {
      str_field = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'int_field' field.
      * @return The value.
      */
    public java.lang.Integer getIntField() {
      return int_field;
    }


    /**
      * Sets the value of the 'int_field' field.
      * @param value The value of 'int_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder setIntField(java.lang.Integer value) {
      validate(fields()[1], value);
      this.int_field = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'int_field' field has been set.
      * @return True if the 'int_field' field has been set, false otherwise.
      */
    public boolean hasIntField() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'int_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder clearIntField() {
      int_field = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'array_field' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getArrayField() {
      return array_field;
    }


    /**
      * Sets the value of the 'array_field' field.
      * @param value The value of 'array_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder setArrayField(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.array_field = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'array_field' field has been set.
      * @return True if the 'array_field' field has been set, false otherwise.
      */
    public boolean hasArrayField() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'array_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder clearArrayField() {
      array_field = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'enum_field' field.
      * @return The value.
      */
    public com.google.cloud.pubsub.prober.Suit getEnumField() {
      return enum_field;
    }


    /**
      * Sets the value of the 'enum_field' field.
      * @param value The value of 'enum_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder setEnumField(com.google.cloud.pubsub.prober.Suit value) {
      validate(fields()[3], value);
      this.enum_field = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'enum_field' field has been set.
      * @return True if the 'enum_field' field has been set, false otherwise.
      */
    public boolean hasEnumField() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'enum_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder clearEnumField() {
      enum_field = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'map_field' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Long> getMapField() {
      return map_field;
    }


    /**
      * Sets the value of the 'map_field' field.
      * @param value The value of 'map_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder setMapField(java.util.Map<java.lang.CharSequence,java.lang.Long> value) {
      validate(fields()[4], value);
      this.map_field = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'map_field' field has been set.
      * @return True if the 'map_field' field has been set, false otherwise.
      */
    public boolean hasMapField() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'map_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder clearMapField() {
      map_field = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'record_field' field.
      * @return The value.
      */
    public com.google.cloud.pubsub.prober.AddressRecord getRecordField() {
      return record_field;
    }


    /**
      * Sets the value of the 'record_field' field.
      * @param value The value of 'record_field'.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder setRecordField(com.google.cloud.pubsub.prober.AddressRecord value) {
      validate(fields()[5], value);
      this.record_fieldBuilder = null;
      this.record_field = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'record_field' field has been set.
      * @return True if the 'record_field' field has been set, false otherwise.
      */
    public boolean hasRecordField() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'record_field' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.google.cloud.pubsub.prober.AddressRecord.Builder getRecordFieldBuilder() {
      if (record_fieldBuilder == null) {
        if (hasRecordField()) {
          setRecordFieldBuilder(com.google.cloud.pubsub.prober.AddressRecord.newBuilder(record_field));
        } else {
          setRecordFieldBuilder(com.google.cloud.pubsub.prober.AddressRecord.newBuilder());
        }
      }
      return record_fieldBuilder;
    }

    /**
     * Sets the Builder instance for the 'record_field' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.google.cloud.pubsub.prober.NullTest.Builder setRecordFieldBuilder(com.google.cloud.pubsub.prober.AddressRecord.Builder value) {
      clearRecordField();
      record_fieldBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'record_field' field has an active Builder instance
     * @return True if the 'record_field' field has an active Builder instance
     */
    public boolean hasRecordFieldBuilder() {
      return record_fieldBuilder != null;
    }

    /**
      * Clears the value of the 'record_field' field.
      * @return This builder.
      */
    public com.google.cloud.pubsub.prober.NullTest.Builder clearRecordField() {
      record_field = null;
      record_fieldBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NullTest build() {
      try {
        NullTest record = new NullTest();
        record.str_field = fieldSetFlags()[0] ? this.str_field : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.int_field = fieldSetFlags()[1] ? this.int_field : (java.lang.Integer) defaultValue(fields()[1]);
        record.array_field = fieldSetFlags()[2] ? this.array_field : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        record.enum_field = fieldSetFlags()[3] ? this.enum_field : (com.google.cloud.pubsub.prober.Suit) defaultValue(fields()[3]);
        record.map_field = fieldSetFlags()[4] ? this.map_field : (java.util.Map<java.lang.CharSequence,java.lang.Long>) defaultValue(fields()[4]);
        if (record_fieldBuilder != null) {
          try {
            record.record_field = this.record_fieldBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("record_field"));
            throw e;
          }
        } else {
          record.record_field = fieldSetFlags()[5] ? this.record_field : (com.google.cloud.pubsub.prober.AddressRecord) defaultValue(fields()[5]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NullTest>
    WRITER$ = (org.apache.avro.io.DatumWriter<NullTest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NullTest>
    READER$ = (org.apache.avro.io.DatumReader<NullTest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.str_field == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.str_field);
    }

    if (this.int_field == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.int_field);
    }

    if (this.array_field == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.array_field.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.CharSequence e0: this.array_field) {
        actualSize0++;
        out.startItem();
        out.writeString(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    if (this.enum_field == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.enum_field.ordinal());
    }

    if (this.map_field == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size1 = this.map_field.size();
      out.writeMapStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.util.Map.Entry<java.lang.CharSequence, java.lang.Long> e1: this.map_field.entrySet()) {
        actualSize1++;
        out.startItem();
        out.writeString(e1.getKey());
        java.lang.Long v1 = e1.getValue();
        out.writeLong(v1);
      }
      out.writeMapEnd();
      if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }

    if (this.record_field == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.record_field.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.str_field = null;
      } else {
        this.str_field = in.readString(this.str_field instanceof Utf8 ? (Utf8)this.str_field : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.int_field = null;
      } else {
        this.int_field = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.array_field = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.CharSequence> a0 = this.array_field;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("array_field").schema().getTypes().get(1));
          this.array_field = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
            a0.add(e0);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.enum_field = null;
      } else {
        this.enum_field = com.google.cloud.pubsub.prober.Suit.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.map_field = null;
      } else {
        long size1 = in.readMapStart();
        java.util.Map<java.lang.CharSequence,java.lang.Long> m1 = this.map_field; // Need fresh name due to limitation of macro system
        if (m1 == null) {
          m1 = new java.util.HashMap<java.lang.CharSequence,java.lang.Long>((int)size1);
          this.map_field = m1;
        } else m1.clear();
        for ( ; 0 < size1; size1 = in.mapNext()) {
          for ( ; size1 != 0; size1--) {
            java.lang.CharSequence k1 = null;
            k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
            java.lang.Long v1 = null;
            v1 = in.readLong();
            m1.put(k1, v1);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.record_field = null;
      } else {
        if (this.record_field == null) {
          this.record_field = new com.google.cloud.pubsub.prober.AddressRecord();
        }
        this.record_field.customDecode(in);
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.str_field = null;
          } else {
            this.str_field = in.readString(this.str_field instanceof Utf8 ? (Utf8)this.str_field : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.int_field = null;
          } else {
            this.int_field = in.readInt();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.array_field = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.CharSequence> a0 = this.array_field;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("array_field").schema().getTypes().get(1));
              this.array_field = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
                a0.add(e0);
              }
            }
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.enum_field = null;
          } else {
            this.enum_field = com.google.cloud.pubsub.prober.Suit.values()[in.readEnum()];
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.map_field = null;
          } else {
            long size1 = in.readMapStart();
            java.util.Map<java.lang.CharSequence,java.lang.Long> m1 = this.map_field; // Need fresh name due to limitation of macro system
            if (m1 == null) {
              m1 = new java.util.HashMap<java.lang.CharSequence,java.lang.Long>((int)size1);
              this.map_field = m1;
            } else m1.clear();
            for ( ; 0 < size1; size1 = in.mapNext()) {
              for ( ; size1 != 0; size1--) {
                java.lang.CharSequence k1 = null;
                k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
                java.lang.Long v1 = null;
                v1 = in.readLong();
                m1.put(k1, v1);
              }
            }
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.record_field = null;
          } else {
            if (this.record_field == null) {
              this.record_field = new com.google.cloud.pubsub.prober.AddressRecord();
            }
            this.record_field.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










