// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.google.cloud.pubsub.prober;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.cloud.pubsub.prober.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string first_name = 1;</code>
     * @return Whether the firstName field is set.
     */
    boolean hasFirstName();
    /**
     * <code>optional string first_name = 1;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>optional string last_name = 2;</code>
     * @return Whether the lastName field is set.
     */
    boolean hasLastName();
    /**
     * <code>optional string last_name = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>optional string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>optional int32 age = 3;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
     * @return The address.
     */
    com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address getAddress();
    /**
     * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
     */
    com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code com.google.cloud.pubsub.prober.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.google.cloud.pubsub.prober.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              firstName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lastName_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              age_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.pubsub.prober.PersonOuterClass.Person.class, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Builder.class);
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.google.cloud.pubsub.prober.Person.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 street_number = 1;</code>
       * @return Whether the streetNumber field is set.
       */
      boolean hasStreetNumber();
      /**
       * <code>optional int32 street_number = 1;</code>
       * @return The streetNumber.
       */
      int getStreetNumber();

      /**
       * <code>optional string street_name = 2;</code>
       * @return Whether the streetName field is set.
       */
      boolean hasStreetName();
      /**
       * <code>optional string street_name = 2;</code>
       * @return The streetName.
       */
      java.lang.String getStreetName();
      /**
       * <code>optional string street_name = 2;</code>
       * @return The bytes for streetName.
       */
      com.google.protobuf.ByteString
          getStreetNameBytes();

      /**
       * <code>optional string city = 3;</code>
       * @return Whether the city field is set.
       */
      boolean hasCity();
      /**
       * <code>optional string city = 3;</code>
       * @return The city.
       */
      java.lang.String getCity();
      /**
       * <code>optional string city = 3;</code>
       * @return The bytes for city.
       */
      com.google.protobuf.ByteString
          getCityBytes();

      /**
       * <code>optional string state = 4;</code>
       * @return Whether the state field is set.
       */
      boolean hasState();
      /**
       * <code>optional string state = 4;</code>
       * @return The state.
       */
      java.lang.String getState();
      /**
       * <code>optional string state = 4;</code>
       * @return The bytes for state.
       */
      com.google.protobuf.ByteString
          getStateBytes();

      /**
       * <code>optional string country = 5;</code>
       * @return Whether the country field is set.
       */
      boolean hasCountry();
      /**
       * <code>optional string country = 5;</code>
       * @return The country.
       */
      java.lang.String getCountry();
      /**
       * <code>optional string country = 5;</code>
       * @return The bytes for country.
       */
      com.google.protobuf.ByteString
          getCountryBytes();

      /**
       * <code>optional string zip = 6;</code>
       * @return Whether the zip field is set.
       */
      boolean hasZip();
      /**
       * <code>optional string zip = 6;</code>
       * @return The zip.
       */
      java.lang.String getZip();
      /**
       * <code>optional string zip = 6;</code>
       * @return The bytes for zip.
       */
      com.google.protobuf.ByteString
          getZipBytes();
    }
    /**
     * Protobuf type {@code com.google.cloud.pubsub.prober.Person.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.google.cloud.pubsub.prober.Person.Address)
        AddressOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        streetName_ = "";
        city_ = "";
        state_ = "";
        country_ = "";
        zip_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Address();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                streetNumber_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                streetName_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                city_ = bs;
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                state_ = bs;
                break;
              }
              case 42: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000010;
                country_ = bs;
                break;
              }
              case 50: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000020;
                zip_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.class, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder.class);
      }

      private int bitField0_;
      public static final int STREET_NUMBER_FIELD_NUMBER = 1;
      private int streetNumber_;
      /**
       * <code>optional int32 street_number = 1;</code>
       * @return Whether the streetNumber field is set.
       */
      @java.lang.Override
      public boolean hasStreetNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 street_number = 1;</code>
       * @return The streetNumber.
       */
      @java.lang.Override
      public int getStreetNumber() {
        return streetNumber_;
      }

      public static final int STREET_NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object streetName_;
      /**
       * <code>optional string street_name = 2;</code>
       * @return Whether the streetName field is set.
       */
      @java.lang.Override
      public boolean hasStreetName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string street_name = 2;</code>
       * @return The streetName.
       */
      @java.lang.Override
      public java.lang.String getStreetName() {
        java.lang.Object ref = streetName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            streetName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string street_name = 2;</code>
       * @return The bytes for streetName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStreetNameBytes() {
        java.lang.Object ref = streetName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CITY_FIELD_NUMBER = 3;
      private volatile java.lang.Object city_;
      /**
       * <code>optional string city = 3;</code>
       * @return Whether the city field is set.
       */
      @java.lang.Override
      public boolean hasCity() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string city = 3;</code>
       * @return The city.
       */
      @java.lang.Override
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string city = 3;</code>
       * @return The bytes for city.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATE_FIELD_NUMBER = 4;
      private volatile java.lang.Object state_;
      /**
       * <code>optional string state = 4;</code>
       * @return Whether the state field is set.
       */
      @java.lang.Override
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string state = 4;</code>
       * @return The state.
       */
      @java.lang.Override
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string state = 4;</code>
       * @return The bytes for state.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int COUNTRY_FIELD_NUMBER = 5;
      private volatile java.lang.Object country_;
      /**
       * <code>optional string country = 5;</code>
       * @return Whether the country field is set.
       */
      @java.lang.Override
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string country = 5;</code>
       * @return The country.
       */
      @java.lang.Override
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            country_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string country = 5;</code>
       * @return The bytes for country.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ZIP_FIELD_NUMBER = 6;
      private volatile java.lang.Object zip_;
      /**
       * <code>optional string zip = 6;</code>
       * @return Whether the zip field is set.
       */
      @java.lang.Override
      public boolean hasZip() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string zip = 6;</code>
       * @return The zip.
       */
      @java.lang.Override
      public java.lang.String getZip() {
        java.lang.Object ref = zip_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zip_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string zip = 6;</code>
       * @return The bytes for zip.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getZipBytes() {
        java.lang.Object ref = zip_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, streetNumber_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, streetName_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, city_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, state_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, country_);
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 6, zip_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, streetNumber_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, streetName_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, city_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, state_);
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, country_);
        }
        if (((bitField0_ & 0x00000020) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, zip_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address)) {
          return super.equals(obj);
        }
        com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address other = (com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address) obj;

        if (hasStreetNumber() != other.hasStreetNumber()) return false;
        if (hasStreetNumber()) {
          if (getStreetNumber()
              != other.getStreetNumber()) return false;
        }
        if (hasStreetName() != other.hasStreetName()) return false;
        if (hasStreetName()) {
          if (!getStreetName()
              .equals(other.getStreetName())) return false;
        }
        if (hasCity() != other.hasCity()) return false;
        if (hasCity()) {
          if (!getCity()
              .equals(other.getCity())) return false;
        }
        if (hasState() != other.hasState()) return false;
        if (hasState()) {
          if (!getState()
              .equals(other.getState())) return false;
        }
        if (hasCountry() != other.hasCountry()) return false;
        if (hasCountry()) {
          if (!getCountry()
              .equals(other.getCountry())) return false;
        }
        if (hasZip() != other.hasZip()) return false;
        if (hasZip()) {
          if (!getZip()
              .equals(other.getZip())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStreetNumber()) {
          hash = (37 * hash) + STREET_NUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getStreetNumber();
        }
        if (hasStreetName()) {
          hash = (37 * hash) + STREET_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getStreetName().hashCode();
        }
        if (hasCity()) {
          hash = (37 * hash) + CITY_FIELD_NUMBER;
          hash = (53 * hash) + getCity().hashCode();
        }
        if (hasState()) {
          hash = (37 * hash) + STATE_FIELD_NUMBER;
          hash = (53 * hash) + getState().hashCode();
        }
        if (hasCountry()) {
          hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
          hash = (53 * hash) + getCountry().hashCode();
        }
        if (hasZip()) {
          hash = (37 * hash) + ZIP_FIELD_NUMBER;
          hash = (53 * hash) + getZip().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.google.cloud.pubsub.prober.Person.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.google.cloud.pubsub.prober.Person.Address)
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_Address_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.class, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder.class);
        }

        // Construct using com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          streetNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          streetName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          city_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          state_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          country_ = "";
          bitField0_ = (bitField0_ & ~0x00000010);
          zip_ = "";
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_Address_descriptor;
        }

        @java.lang.Override
        public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address getDefaultInstanceForType() {
          return com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance();
        }

        @java.lang.Override
        public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address build() {
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address buildPartial() {
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address result = new com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.streetNumber_ = streetNumber_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.streetName_ = streetName_;
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.city_ = city_;
          if (((from_bitField0_ & 0x00000008) != 0)) {
            to_bitField0_ |= 0x00000008;
          }
          result.state_ = state_;
          if (((from_bitField0_ & 0x00000010) != 0)) {
            to_bitField0_ |= 0x00000010;
          }
          result.country_ = country_;
          if (((from_bitField0_ & 0x00000020) != 0)) {
            to_bitField0_ |= 0x00000020;
          }
          result.zip_ = zip_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address) {
            return mergeFrom((com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address other) {
          if (other == com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance()) return this;
          if (other.hasStreetNumber()) {
            setStreetNumber(other.getStreetNumber());
          }
          if (other.hasStreetName()) {
            bitField0_ |= 0x00000002;
            streetName_ = other.streetName_;
            onChanged();
          }
          if (other.hasCity()) {
            bitField0_ |= 0x00000004;
            city_ = other.city_;
            onChanged();
          }
          if (other.hasState()) {
            bitField0_ |= 0x00000008;
            state_ = other.state_;
            onChanged();
          }
          if (other.hasCountry()) {
            bitField0_ |= 0x00000010;
            country_ = other.country_;
            onChanged();
          }
          if (other.hasZip()) {
            bitField0_ |= 0x00000020;
            zip_ = other.zip_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int streetNumber_ ;
        /**
         * <code>optional int32 street_number = 1;</code>
         * @return Whether the streetNumber field is set.
         */
        @java.lang.Override
        public boolean hasStreetNumber() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int32 street_number = 1;</code>
         * @return The streetNumber.
         */
        @java.lang.Override
        public int getStreetNumber() {
          return streetNumber_;
        }
        /**
         * <code>optional int32 street_number = 1;</code>
         * @param value The streetNumber to set.
         * @return This builder for chaining.
         */
        public Builder setStreetNumber(int value) {
          bitField0_ |= 0x00000001;
          streetNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 street_number = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearStreetNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          streetNumber_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object streetName_ = "";
        /**
         * <code>optional string street_name = 2;</code>
         * @return Whether the streetName field is set.
         */
        public boolean hasStreetName() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional string street_name = 2;</code>
         * @return The streetName.
         */
        public java.lang.String getStreetName() {
          java.lang.Object ref = streetName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              streetName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string street_name = 2;</code>
         * @return The bytes for streetName.
         */
        public com.google.protobuf.ByteString
            getStreetNameBytes() {
          java.lang.Object ref = streetName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            streetName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string street_name = 2;</code>
         * @param value The streetName to set.
         * @return This builder for chaining.
         */
        public Builder setStreetName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          streetName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string street_name = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearStreetName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          streetName_ = getDefaultInstance().getStreetName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string street_name = 2;</code>
         * @param value The bytes for streetName to set.
         * @return This builder for chaining.
         */
        public Builder setStreetNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          streetName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object city_ = "";
        /**
         * <code>optional string city = 3;</code>
         * @return Whether the city field is set.
         */
        public boolean hasCity() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional string city = 3;</code>
         * @return The city.
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              city_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string city = 3;</code>
         * @return The bytes for city.
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string city = 3;</code>
         * @param value The city to set.
         * @return This builder for chaining.
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearCity() {
          bitField0_ = (bitField0_ & ~0x00000004);
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 3;</code>
         * @param value The bytes for city to set.
         * @return This builder for chaining.
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          city_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object state_ = "";
        /**
         * <code>optional string state = 4;</code>
         * @return Whether the state field is set.
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional string state = 4;</code>
         * @return The state.
         */
        public java.lang.String getState() {
          java.lang.Object ref = state_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              state_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string state = 4;</code>
         * @return The bytes for state.
         */
        public com.google.protobuf.ByteString
            getStateBytes() {
          java.lang.Object ref = state_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            state_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string state = 4;</code>
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string state = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000008);
          state_ = getDefaultInstance().getState();
          onChanged();
          return this;
        }
        /**
         * <code>optional string state = 4;</code>
         * @param value The bytes for state to set.
         * @return This builder for chaining.
         */
        public Builder setStateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          state_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object country_ = "";
        /**
         * <code>optional string country = 5;</code>
         * @return Whether the country field is set.
         */
        public boolean hasCountry() {
          return ((bitField0_ & 0x00000010) != 0);
        }
        /**
         * <code>optional string country = 5;</code>
         * @return The country.
         */
        public java.lang.String getCountry() {
          java.lang.Object ref = country_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              country_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string country = 5;</code>
         * @return The bytes for country.
         */
        public com.google.protobuf.ByteString
            getCountryBytes() {
          java.lang.Object ref = country_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string country = 5;</code>
         * @param value The country to set.
         * @return This builder for chaining.
         */
        public Builder setCountry(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          country_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string country = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearCountry() {
          bitField0_ = (bitField0_ & ~0x00000010);
          country_ = getDefaultInstance().getCountry();
          onChanged();
          return this;
        }
        /**
         * <code>optional string country = 5;</code>
         * @param value The bytes for country to set.
         * @return This builder for chaining.
         */
        public Builder setCountryBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          country_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object zip_ = "";
        /**
         * <code>optional string zip = 6;</code>
         * @return Whether the zip field is set.
         */
        public boolean hasZip() {
          return ((bitField0_ & 0x00000020) != 0);
        }
        /**
         * <code>optional string zip = 6;</code>
         * @return The zip.
         */
        public java.lang.String getZip() {
          java.lang.Object ref = zip_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              zip_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string zip = 6;</code>
         * @return The bytes for zip.
         */
        public com.google.protobuf.ByteString
            getZipBytes() {
          java.lang.Object ref = zip_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            zip_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string zip = 6;</code>
         * @param value The zip to set.
         * @return This builder for chaining.
         */
        public Builder setZip(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          zip_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string zip = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearZip() {
          bitField0_ = (bitField0_ & ~0x00000020);
          zip_ = getDefaultInstance().getZip();
          onChanged();
          return this;
        }
        /**
         * <code>optional string zip = 6;</code>
         * @param value The bytes for zip to set.
         * @return This builder for chaining.
         */
        public Builder setZipBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          zip_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.google.cloud.pubsub.prober.Person.Address)
      }

      // @@protoc_insertion_point(class_scope:com.google.cloud.pubsub.prober.Person.Address)
      private static final com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address();
      }

      public static com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        @java.lang.Override
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>optional string first_name = 1;</code>
     * @return Whether the firstName field is set.
     */
    @java.lang.Override
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string first_name = 1;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string first_name = 1;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>optional string last_name = 2;</code>
     * @return Whether the lastName field is set.
     */
    @java.lang.Override
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string last_name = 2;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last_name = 2;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>optional int32 age = 3;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address address_;
    /**
     * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
     * @return The address.
     */
    @java.lang.Override
    public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address getAddress() {
      return address_ == null ? com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
     */
    @java.lang.Override
    public com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance() : address_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, age_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.cloud.pubsub.prober.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      com.google.cloud.pubsub.prober.PersonOuterClass.Person other = (com.google.cloud.pubsub.prober.PersonOuterClass.Person) obj;

      if (hasFirstName() != other.hasFirstName()) return false;
      if (hasFirstName()) {
        if (!getFirstName()
            .equals(other.getFirstName())) return false;
      }
      if (hasLastName() != other.hasLastName()) return false;
      if (hasLastName()) {
        if (!getLastName()
            .equals(other.getLastName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFirstName()) {
        hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
      }
      if (hasLastName()) {
        hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.cloud.pubsub.prober.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.cloud.pubsub.prober.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.cloud.pubsub.prober.Person)
        com.google.cloud.pubsub.prober.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.cloud.pubsub.prober.PersonOuterClass.Person.class, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Builder.class);
      }

      // Construct using com.google.cloud.pubsub.prober.PersonOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.cloud.pubsub.prober.PersonOuterClass.internal_static_com_google_cloud_pubsub_prober_Person_descriptor;
      }

      @java.lang.Override
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person getDefaultInstanceForType() {
        return com.google.cloud.pubsub.prober.PersonOuterClass.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person build() {
        com.google.cloud.pubsub.prober.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person buildPartial() {
        com.google.cloud.pubsub.prober.PersonOuterClass.Person result = new com.google.cloud.pubsub.prober.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (addressBuilder_ == null) {
            result.address_ = address_;
          } else {
            result.address_ = addressBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.cloud.pubsub.prober.PersonOuterClass.Person) {
          return mergeFrom((com.google.cloud.pubsub.prober.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.cloud.pubsub.prober.PersonOuterClass.Person other) {
        if (other == com.google.cloud.pubsub.prober.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000001;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000002;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.cloud.pubsub.prober.PersonOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.cloud.pubsub.prober.PersonOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string first_name = 1;</code>
       * @return Whether the firstName field is set.
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string first_name = 1;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string first_name = 1;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string first_name = 1;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 1;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string last_name = 2;</code>
       * @return Whether the lastName field is set.
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string last_name = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_name = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_name = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 3;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000004;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder, com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       * @return The address.
       */
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      public Builder setAddress(com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      public Builder setAddress(
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      public Builder mergeAddress(com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              address_ != null &&
              address_ != com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance()) {
            address_ =
              com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      public com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .com.google.cloud.pubsub.prober.Person.Address address = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder, com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder>
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address, com.google.cloud.pubsub.prober.PersonOuterClass.Person.Address.Builder, com.google.cloud.pubsub.prober.PersonOuterClass.Person.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.google.cloud.pubsub.prober.Person)
    }

    // @@protoc_insertion_point(class_scope:com.google.cloud.pubsub.prober.Person)
    private static final com.google.cloud.pubsub.prober.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.cloud.pubsub.prober.PersonOuterClass.Person();
    }

    public static com.google.cloud.pubsub.prober.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.cloud.pubsub.prober.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_pubsub_prober_Person_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_pubsub_prober_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_pubsub_prober_Person_Address_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_pubsub_prober_Person_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\036com.google.cloud.pubsub." +
      "prober\"\357\001\n\006Person\022\022\n\nfirst_name\030\001 \001(\t\022\021\n" +
      "\tlast_name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022?\n\007address" +
      "\030\004 \001(\0132..com.google.cloud.pubsub.prober." +
      "Person.Address\032p\n\007Address\022\025\n\rstreet_numb" +
      "er\030\001 \001(\005\022\023\n\013street_name\030\002 \001(\t\022\014\n\004city\030\003 " +
      "\001(\t\022\r\n\005state\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\013\n\003z" +
      "ip\030\006 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_google_cloud_pubsub_prober_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_cloud_pubsub_prober_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_pubsub_prober_Person_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Age", "Address", });
    internal_static_com_google_cloud_pubsub_prober_Person_Address_descriptor =
      internal_static_com_google_cloud_pubsub_prober_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_google_cloud_pubsub_prober_Person_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_pubsub_prober_Person_Address_descriptor,
        new java.lang.String[] { "StreetNumber", "StreetName", "City", "State", "Country", "Zip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
