/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.google.cloud.pubsub.prober;
@org.apache.avro.specific.AvroGenerated
public enum Suit implements org.apache.avro.generic.GenericEnumSymbol<Suit> {
  SPADES, HEARTS, DIAMONDS, CLUBS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Suit\",\"namespace\":\"com.google.cloud.pubsub.prober\",\"symbols\":[\"SPADES\",\"HEARTS\",\"DIAMONDS\",\"CLUBS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
